image: node:22

definitions:
    caches:
        cache: ~/.cache
    steps:
        - step: &release
              name: release
              caches:
                  - cache
              script:
                  - npx -p semantic-release -p @semantic-release/changelog -p @semantic-release/git semantic-release
        - step: &github-sync
              name: Sync to GitHub
              clone:
                  depth: full
              script:
                  - git fetch origin master --tags
                  - git checkout master
                  - git remote add github https://${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/gopaycommunity/gopay-ios-sdk.git || true
                  - git fetch github
                  - git push github master --force-with-lease
                  - git push github --tags
        - step: &sonarcloud-analysis
              name: sonar
              caches:
                  - node
              clone:
                  depth: full # SonarCloud scanner needs the full history to assign issues properly
              script:
                  -   pipe: sonarsource/sonarcloud-scan:4.1.0
                      variables:
                          EXTRA_ARGS: >
                            -Dsonar.c.file.suffixes=-
                            -Dsonar.cpp.file.suffixes=-
                            -Dsonar.objc.file.suffixes=-
                  -   pipe: sonarsource/sonarcloud-quality-gate:0.1.6

pipelines:
    branches:
        master:
            - parallel:
                - step: *release
                - step: *sonarcloud-analysis
            - step: *github-sync
    pull-requests:
        '**':
            - parallel:
                - step: *sonarcloud-analysis
    custom:
        github-sync:
            - step: *github-sync
