# SonarCloud configuration
sonar.projectKey=gp-gopay_gp-gw-ios-sdk
sonar.organization=gp-gopay

# Sources
sonar.sources=sdk/sdk

# Tests
sonar.tests=sdk/sdkTests
sonar.test.inclusions=**/*Tests.swift

# Encoding of the source code
sonar.sourceEncoding=UTF-8
